### ISSUE TITLE
there isn't Edit >Theme

### ISSUE THREAD

**Issue by RealSting** [zackelia/ghidra-dark-theme#1]
Hi,
thanks for this theme!
anyway there isn't Edit > Theme
![image](https://github.com/zackelia/ghidra-dark-theme/assets/4011479/2de38c52-c18c-4f32-94d9-987b9af0ffcc)

I'm on CodeBrowser:
![image](https://github.com/zackelia/ghidra-dark-theme/assets/4011479/1cbbb4f2-5309-4a54-ac06-6c43c360e257)

Cheers,

**Comment by zackelia** [comment]
The theme options are only available in the edit menu for the _main_ Ghidra view, not the CodeBrowser view.
